theme: jekyll-theme-cayman
title: Analyzing Customer Sentiments And Topics Of Food Delivery Platforms Through App Store Reviews
description: Leveraging NLP Analysis Techniques To Classify Review Sentiments And Model Topics Of Food Delivery App Store Reviews